### ISSUE TITLE
Doesn't work wih Silverstripe 3.1.14 +

### ISSUE THREAD

**Issue by ipalette** [silverstripe-labs/silverstripe-dms#66] opened 2015-09-27 13:20 UTC
Something changed which breaks the link with the document. In 3.1.13 the module still works.

Example:

/dmsdocument/1

Shows:
This asset does not exist.

**Comment by sheadawson** [comment] 2015-10-22 03:36
This issue seems to be caused by the Folder field not being set on the DMSDocument model when a new document is uploaded

**Comment by jeffwhitfield** [comment] 2016-01-14 17:08
Added a fix here:

https://github.com/silverstripe-labs/silverstripe-dms/pull/73

Problem was that the Folder field needed to be set as a string instead of an integer when being saved to the database.

**Comment by jeffwhitfield** [comment] 2016-01-22 00:47
Updated pull request here:

https://github.com/silverstripe-labs/silverstripe-dms/pull/75

Problem was that the Folder field needed to be set as a string instead of an integer when being saved to the database. This is likely due to some changes that requires values to be cast matching the type expected in the database.

**Comment by xini** [comment] 2016-07-18 03:22
can be closed, #75 is merged.

**Closed** 2016-07-18 10:49 UTC
